channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - compas==0.17.2
  - compas_fab==0.13.1
  - compas_mobile_robot_reloc==1.0.4
  - pip
  - pip:
    # non conda dependencies
    - pyrealsense2
    - open3d
    # code style tools
    - flake8
    - autopep8
    - pylint
    - isort
    # testing tools
    - pytest
    - ironpython-pytest
    # autocomplete for Rhino
    - Rhino-stubs
    - Grasshopper-stubs
